### ISSUE TITLE
fix various bug

### ISSUE THREAD

**Issue by jrestuccio** [UofM-Capstone-HOA/HOA#23]
Fix any bugs I find, presenting to client tomorrow.

**Comment by jrestuccio** [comment]
fixed homeowner show button on admin page.

**Comment by jrestuccio** [comment]
made issue categories look like homeowners on admin page.
Good styling etc.

**Comment by jrestuccio** [comment]
fixed back links where I found them. in issue categories

<%= link_to 'Back', admin_path(current_user) %>

**Comment by jrestuccio** [comment]
added routes link

**Comment by kevinatown** [comment]
Merged branch. Closing issue.
