### ISSUE TITLE
Create Routes page

### ISSUE THREAD

**Issue by jrestuccio** [UofM-Capstone-HOA/HOA#31]
Create the routes page and install necessary gems

**Comment by jrestuccio** [comment]
Routes page has been created. The map is working, and will detect your location.
I added custom map markers that will pull issue details and display differently based on their issue_status.
GeoCoder automatically adds latitude and longitude when creating an address.

We need to look into caching the geodata so we don't request it every time. Should make app run faster.

**Comment by kevinatown** [comment]
Issue is finished. Closing
