### ISSUE TITLE
Create Admin Page/Logic

### ISSUE THREAD

**Issue by kevinatown** [UofM-Capstone-HOA/HOA#9]
The Admin page will be created allowing an admin to assign security privileges to other users.  This way only admins can create/edit issue categories.

**Comment by kevinatown** [comment]
Still some issues remain. Will add more notes later

**Comment by jrestuccio** [comment]
Added logic so Admin link only appears for users with their "isadmin" attribute set to True (1).

**Comment by kevinatown** [comment]
Task complete closing issue.
